import { SiteShell } from "@/components/prada/SiteShell";
import { ArtistPersona } from "@/components/future/artist-persona/ArtistPersona";
import { NextModuleCta } from "@/components/NextModuleCta";

export default function ArtistPersonaPage() {
  return (
    <SiteShell>
      <section className="pt-14 md:pt-20 px-6 md:px-10" aria-labelledby="artist-heading">
        <div className="mx-auto max-w-[1140px]">
          <p className="prada-mono-caps text-[10px] text-black/45">AI Artist Persona</p>
          <h1
            id="artist-heading"
            className="prada-display mt-3 text-[30px] md:text-[44px] leading-[1.08] max-w-[22ch]"
          >
            Talk to the painter.
          </h1>
          <p className="prada-body mt-5 text-[15px] md:text-[16px] leading-[1.65] text-black/65 max-w-[56ch]">
            Pick a painter from the collection and ask them anything: about a brushstroke,
            a memory, a dream. They answer in their own voice, about their own work.
          </p>
        </div>
      </section>

      <section className="pt-10 md:pt-14 pb-20 md:pb-28 px-6 md:px-10">
        <div className="mx-auto max-w-[1140px]">
          <ArtistPersona />
          <p
            role="note"
            className="prada-body mt-8 max-w-[64ch] text-[12.5px] leading-[1.6] text-black/45"
          >
            Responses are generated by AI from publicly available information about each
            artist. They may contain inaccuracies: treat them as creative interpretation,
            not historical fact.
          </p>
          <div className="mt-8">
            <NextModuleCta fromSlug="artist-persona" />
          </div>
        </div>
      </section>
    </SiteShell>
  );
}
